"Get rid of mysterious 'Error registering CheckBoxList'
This used to be displayed on startup (without impact on functionality):

---
pyrna_srna_Subtype: error registering 'CheckBoxList'
TypeError: metaclass conflict: the metaclass of a derived class must be a
    (non-strict) subclass of the metaclasses of all its bases
---

For some reason, making CheckBoxList not inherit from UIList (and
instead using multiple inheritance) fixed the warning.